$('.next-btn1').click(function(){
    $('.first-step').hide();
    $('.second-step').show();
    $('.step2').addClass('active');
});
$('.next-btn2').click(function(){
    $('.second-step').hide();
    $('.third-step').show();
    $('.step3').addClass('active');
});
$('.next-btn3').click(function(){
    $('.third-step').hide();
    $('.fourth-step').show();
    $('.step4').addClass('active');
});
